### PR TITLE
fix: log branch name when starting commitsar

### LINKED ISSUE #200: Branch name not present in log output
#167 reported that branch name is not printed in the output when starting commitsar.

### PR DESCRIPTION
**Pull request by fallion**
Closes #200

### CODE REVIEW

File: internal/root_runner/log_branch_test.go [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+		Logger:      &testLogger,
+		Strict:      false,
+		Debug:       false,
+	}
+
+	gitRepo, err := history.OpenGit("../../testdata/commits-on-master", nil)
+
+	assert.NoError(t, err)
+
+	runner.logBranch(gitRepo)
```
Comment (golangcibot) [inline internal/root_runner/log_branch_test.go]: Error return value of `runner.logBranch` is not checked (from `errcheck`)
